# Generated by Django 5.1.5 on 2025-05-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
