# Generated by Django 5.0.6 on 2025-06-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_perfilusuario_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayorista',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
