# Generated by Django 5.0.6 on 2025-06-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_producto_precio_mayorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empresa',
            field=models.BooleanField(db_default=False),
        ),
    ]
