# Generated by Django 5.2.1 on 2025-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='order_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='buy_order',
            field=models.CharField(default=1, max_length=26, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
