# Generated by Django 5.2.1 on 2025-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_remove_pedido_order_id_pedido_buy_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='buy_order',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
    ]
