# Generated by Django 5.2.1 on 2025-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_rename_buy_order_pedido_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='precio',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
