# Generated by Django 5.0.6 on 2025-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_pedido_comuna_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
