# Generated by Django 5.0.6 on 2025-06-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_producto_alto_producto_ancho_producto_largo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_comuna_chilexpress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
