# Generated by Django 5.0.6 on 2025-06-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_pedido_codigo_comuna_chilexpress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='peso_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
