# Generated by Django 5.0.6 on 2025-06-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_pedido_peso_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='alto',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='ancho',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='largo',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
