# Generated by Django 5.0.6 on 2025-06-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_pedido_alto_pedido_ancho_pedido_largo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='alto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ancho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='largo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
